// Students
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const EDIT_STUDENT_SUCCESS = 'EDIT_STUDENT_SUCCESS';

export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS';

